name: DABs Deployment

on:
  push:
    branches: [development, release, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy to DEV
        run: databricks bundle deploy -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          # Al NO enviar un TOKEN y enviar estas 3, la CLI se vuelve el SP
          ARM_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID_DEV }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET_DEV }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#      
#      - name: Deploy to DEV
#        if: github.ref == 'refs/heads/development'
#        run: databricks bundle deploy -t dev
#        env:
#          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
#          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}

#      - name: Deploy to QA
#        if: github.ref == 'refs/heads/release'
#        run: databricks bundle deploy -t qa
#        env:
#          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_QA }}
#          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_QA }}